export const orderAttrLabelMap: Record<string, string> = {
    id: 'Mã đơn',
    type: 'Loại đơn',
    measure: 'Số đo',
    consumer_id: 'Mã KH',
    fullname: 'Khách hàng',
    facebook_link: 'Facebook KH',
    created_at: 'Ngày thêm',
    address: 'Địa chỉ',
    deadline_at: 'DEADLINE',
    total: 'Tổng đơn',
    total_paid: 'Đã trả',
    image: 'Hình ảnh',
    status: 'Trạng thái',
    note: 'Ghi chú',
    props: 'Phụ kiện',
    parent_id: 'Đơn parent',
}
